apiVersion: v1
kind: Pod
metadata:
  name: gpu-version
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: nvcr.io/nvidia/pytorch:25.06-py3 						 #更换成你本地的gpu镜像

    resources:
      limits:
        nvidia.com/gpu: 1
    command: ["bash","-lc"]
    args:
      - |
        python - <<'PY'
        import torch
        print("CUDA:", torch.cuda.is_available())
        if torch.cuda.is_available():
            print("GPU:", torch.cuda.get_device_name(0))
        PY

